### ISSUE TITLE
Use Environment Variables instead of CLI Arguments

### ISSUE THREAD

**Issue by insipx** [xmtp/didethresolver#11]
### Is your feature request related to a problem?

We will generally be running the gateway as a dockerfile deployment or otherwise, so it will be easier to set environment variables rather than CLI Arguments. Environment variables are better if we ever need to set an APIKEY for our ethereum provider, since these variables may be encrypted secrets. Additionally we can change the arguments without rebuilding the docker image.

didethresolver currently defines two command line arguments in it's `lib.rs`:

```rust
#[derive(FromArgs)]
/// DID Ethereum Resolver XMTP Gateway
struct DidEthGatewayApp {
    /// the address to start the server
    #[argh(option, short = 'a', default = "String::from(\"127.0.0.1:9944\")")]
    address: String,

    /// ethereum RPC Provider
    #[argh(
        option,
        short = 'p',
        default = "String::from(\"wss://eth.llamarpc.com\")"
    )]
    provider: String,
}
```

**Comment by jac18281828** [comment]
What do you think of using dotenv for this?

**Comment by insipx** [comment]
dotenv is good
