### ISSUE TITLE
Terraform/Devops initial deployment

### ISSUE THREAD

**Issue by insipx** [xmtp/didethresolver#26]
### Is your feature request related to a problem?

initial terraform scripts/deployment

**Comment by snormore** [comment]
@insipx @jac18281828 Do we actually need to deploy this as a separate service that the gateway calls into, vs just using it as a library with something like https://github.com/xmtp/didethresolver/blob/main/src/rpc/methods.rs#L30-L34 directly in the gateway's `fetch_installation` rpc method?

**Comment by insipx** [comment]
afaiu, the resolver will not be used by the other gateways, rather by users who need access to DID Documents

We will be using the didethresolver as library in the other gateways. This brings up a good question though, who else is planning on using the resolver? @jac18281828

**Comment by jac18281828** [comment]
> afaiu, the resolver will not be used by the other gateways, rather by users who need access to DID Documents
> 
> We will be using the didethresolver as library in the other gateways. This brings up a good question though, who else is planning on using the resolver? @jac18281828

We need to consider the tradeoff between infrastructure deployment of 2 services in Terraform vs bundling a library in two places.     We can discuss in our upcoming infrastructure meeting.
